<a href="https://colab.research.google.com/github/YuvrajRakheja/ANN/blob/main/Tensorflow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.0


==>Tensorflow(Basic Functions) 

1.ANN Build

2.How to select number of hidden layers and neurons

3.Keras -Tuner(DL==>Randomized Search CV

In [3]:
import tensorflow as tf
print("Tensorflow version:{}".format(tf.__version__))
print("Keras version:{}".format(tf.keras.__version__))

Tensorflow version:2.8.0
Keras version:2.8.0


In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [5]:
k=tf.constant(42)

In [6]:
k

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [7]:
a=tf.constant([[4,2],[9,5]])

In [8]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [11]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 6],
       [0, 5]], dtype=int32)>

In [13]:
tf.random.normal(shape=(2,2),mean=0.0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.26463163, -0.5338081 ],
       [-0.90587   , -0.89413345]], dtype=float32)>

In [14]:
a1 = tf.constant([[3,4,5], [3,4,5]])
a2= tf.constant([[1,2,3], [1,2,3]])

c=tf.add(a1,a2)


In [15]:
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 6, 8],
       [4, 6, 8]], dtype=int32)>

In [16]:
d=tf.Variable(23)


In [22]:
tensor = tf.Variable([ [ [10, 1, 12], [13, 14, 15] ], [ [16, 17, 18], [19, 20, 21] ] ,[[3, 4, 5],[8, 9, 10]]]) # tensor variable
print(tensor.shape)

(3, 2, 3)


In [25]:
tensor1 = tf.reshape(tensor,[3,6])

In [26]:
tensor1

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[10,  1, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  8,  9, 10]], dtype=int32)>

In [27]:
tensor1.numpy()

array([[10,  1, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  8,  9, 10]], dtype=int32)